# Site settings
title: Dong Liang's CV 
description: ddbullfrog's CV
favicon: /assets/img/avatar.JPG
baseurl: https://sai-01.github.io/resumecard
url: https://sai-01.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Siting Xu
  title: Java Developer
  address: Guangdong, Shenzhen
  email: sitingxu_01#foxmail.com
  link: https://sai-01.github.io/resumecard/
  weibo:
  github: sai-01
  linkedin: //
  twitter: //
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow: //
  workHistory:
    - work1:
      company: XXX Ltd
      location: Guangdong, Shenzhen
      title: Java Developer
      started: 2023
      duration: (2014 - Present)
      description: I am not a description.
    - work2:
      company: XXX Ltd
      location: Guangdong, Shenzhen
      title: Java Developer
      started: 2022
      duration: (2012 - 2014)
      description: I am not a description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Guangdong, Shenzhen
      degree: Bachelor
      major: Computer Science
      started: 2019
      duration: (2019 - 2023)
      description: I am not a description. 
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Java
      percentage: 80%
    - skill2:
      name: Python
      percentage: 70%
    - skill3:
      name: JavaScript
      percentage: 50%
